# Markdown流水转Excel工具配置文件示例
# 本文件展示了所有可配置的选项和默认值

# 解析规则配置
parsing_rules:
  # 日期行匹配模式 (匹配 ## 2025-09-09 格式)
  date_pattern: "## (\\d{4}-\\d{2}-\\d{2})"

  # 记录条目匹配模式
  entry_pattern: "### (.+?)(?=###|##|$)"

  # 是否启用从标题行提取客户姓名 (处理"### 客户姓名：张三"这种格式)
  header_name_extraction: true

  # 标题行姓名提取模式 (按优先级排序)
  header_name_patterns:
    - "^客户姓名[：:]\\s*(.+?)(?:\\s|$)"  # 匹配 "客户姓名：张三"
    - "^姓名[：:]\\s*(.+?)(?:\\s|$)"      # 匹配 "姓名：张三"
    - "^(.+?)(?:\\s|$)"                   # 直接匹配姓名 (作为最后备选)

  # 字段提取规则 - 可以自定义添加更多字段
  field_patterns:
    姓名: "姓名[：:]\\s*([^；;]+)"
    交易笔数: "交易笔数[：:]\\s*([^；;]+)"
    交易金额: "交易金额[：:]\\s*([^；;]+)"
    交易日期: "交易日期[：:]\\s*([^；;]+)"
    交易时间: "交易时间[：:]\\s*([^；;]+)"
    交易流水号: "交易流水号[/订单号/交易单号/流水号]*[：:]\\s*([^；;]+)"
    支付方式: "支付方式[：:]\\s*([^；;]+)"
    商户: "商户[：:]\\s*([^；;]+)"
    备注: "备注[：:]\\s*([^；;]+)"

    # 自定义字段示例 - 可以添加更多
    # 产品名称: "产品[：:]\\s*([^；;]+)"
    # 订单状态: "状态[：:]\\s*([^；;]+)"
    # 手续费: "手续费[：:]\\s*([^；;]+)"

# 输出设置
output_settings:
  # Excel文件名模板 ({timestamp} 会被替换为时间戳)
  excel_filename: "交易流水转换_{timestamp}.xlsx"

  # 主数据表名称
  sheet_name: "交易记录"

  # 是否包含汇总表
  include_summary: true

  # 是否自动调整列宽
  auto_resize_columns: true

# 数据验证规则
validation:
  # 必填字段列表 - 这些字段为空的记录将被跳过
  required_fields:
    - "姓名"
    - "交易金额"

  # 是否启用金额验证 (检查金额格式是否正确)
  amount_validation: true

  # 是否启用日期验证 (检查日期格式是否正确)
  date_validation: true

# 高级配置选项
advanced:
  # 数据清理选项
  data_cleaning:
    # 移除金额中的逗号分隔符
    remove_amount_commas: true

    # 统一日期格式
    normalize_dates: true

    # 清理多余的空白字符
    trim_whitespace: true

  # 汇总表配置
  summary_options:
    # 生成按日期汇总表
    daily_summary: true

    # 生成按支付方式汇总表
    payment_method_summary: true

    # 生成按客户汇总表
    customer_summary: true

    # 生成按商户汇总表
    merchant_summary: false